### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Nichenstein** [hueyyeng/VesperiaTools#4]
Thanks allot for this ! I have a few problems building HyotoTools... im missing some visual studio console C++ tools idk witch one though.
Anyways before investing more time in finding a way to build them i wanted to ask if its possible to mod data file releted to enemy battle size? any way to make a mod adding more enemies in battle?

**Comment by hueyyeng** [comment]
I have access to CheatEngine but it will take me some time to figure out
which values are responsible for the number of enemies.

As for HyoutaTools, I'm using VS 2017 but I can't exactly remember the
exact the dependencies.

**Comment by Nichenstein** [comment]
Thanks for the reply ! I ll be waiting than. Appreciating the effort !

**Comment by Nichenstein** [comment]
So i m guessing no luck finding the values...

**Comment by hueyyeng** [comment]
Sorry for the late reply as there was a death in my family last Wednesday.
I couldn't do much to find the exact functions that spawn the number of
enemies except for manipulating their stats.

My advise is to ask the folks over at this forum thread:
https://fearlessrevolution.com/threads/8513/

**Comment by Nichenstein** [comment]
No worries, my condolences... Thanks for reply ! Have a nice day and good health to your family !
