### ISSUE TITLE
Texture Pull

### ISSUE THREAD

**Issue by Gunlaus** [hueyyeng/VesperiaTools#6]
Greetings,

I've got the PC version of Vesperia and I would like to know how do I use this in conjunction with Hyouta to pull town/dungeon textures from the game? Would really appreciate a step-by-step as I have no knowledge of CLI usage. Thank you!

**Comment by hueyyeng** [comment]
I'll be creating a GUI soon so it should be easier for those unfamiliar with CLI. Hopefully can get it ready by end of next week but no guarantee.

As for HyoutaTools, are you familiar with compiling an executable with Visual Studio? I'm afraid I can't share the compiled exe on this repo but I can share mine through other methods like email.

**Comment by Gunlaus** [comment]
I've got HyoutaTools compiled and ready, it's just the next step I'm confused about. I've also got UI.svo unpacked with quickbms and I can see the textures in .txm and .txv formats, just no clue what to do with those files. I need them in .dds format. A GUI would be immensely helpful but I also wouldn't mind a basic step by step to better understand what I need to do. Thanks.

**Comment by hueyyeng** [comment]
Good to know! If I'm not mistaken, TXM is the Texture Material (still not clue on reverse engineering it except it reference the texture file in TXV).

All the texture files are stored in TXV. Just be warned that you will see many duplicate textures across different TXVs as the dev try to optimise it from the 360 era where the game loads from DVD.

Although the textures for Definitive Edition are higher resolution from the 360 and PS3 releases! No idea about the Switch version.

**Comment by Gunlaus** [comment]
Yup. I've pulled some textures with Ninjaripper and they're extremely high quality. Now I just need to take all of them (towns/dungeons textures) and train ESRGAN to create a model specifically for Tales/Tales-like games. Will be paramount for my personal project (ToTA HD) and other people's projects as well. This is my only and final hurdle.

**Comment by hueyyeng** [comment]
@Gunlaus For the GUI, I'm using PySide2 which you will need to install through pip.

I already QA tested locally and it works fine. For the TXM/TXV path, the folder must have both the TXM and TXV files for it to work properly as HyoutaTools requires both files.

The new changes is in the develop branch. Do read the README.md on setting up the virtual environments. It is optional but I'll assume you're not familiar with Python.

If all is good, I'll close this issue.

**Comment by Gunlaus** [comment]
On it. Give me 2 hours and I'll be able to test this out. Thanks.

**Comment by hueyyeng** [comment]
Forgot to mentioned that HyoutaTools by default will use the same location for the extracted textures. Refer to the screenshot:

![image](https://user-images.githubusercontent.com/15846423/111075759-6ed98c80-8524-11eb-87a3-aa0dfe461d93.png)

![image](https://user-images.githubusercontent.com/15846423/111075776-7ef16c00-8524-11eb-96c4-2bd043481a3d.png)

Ignore the last two thumbnails as it is DDS with premultiplied alpha that looks fine in Photoshop and XNView MP.

**Comment by Gunlaus** [comment]
Your GUI worked perfectly. Quick question, are map textures not stored in UI.svo? Or is it in map.svo?

(If it is, mind sharing how to unpack the .dat files?)

**Comment by hueyyeng** [comment]
> 
> 
> Your GUI worked perfectly. Quick question, are map textures not stored in UI.svo? Or is it in map.svo?
> 
> (If it is, mind sharing how to unpack the .dat files?)

That will be `map.svo`. You can refer to `unpack_dat` function in `utils/files.py` but it will need some tweak to the `HYOUTATOOLS` constants.

I'll see if I can bolt in `unpack_dat` to the GUI later after work.

**Comment by hueyyeng** [comment]
@Gunlaus I'm closing this issue since the last pull request covers the original scope.

Do continue the discussion here https://github.com/hueyyeng/VesperiaTools/issues/8
