### ISSUE TITLE
Missing DAT and SVO functions in GUI

### ISSUE THREAD

**Issue by hueyyeng** [hueyyeng/VesperiaTools#8]
![image](https://user-images.githubusercontent.com/15846423/111097791-27cbb580-857d-11eb-9ebd-637192f1fc82.png)

Need to implement Unpack DAT and Extract SVO in GUI. Raised by https://github.com/Gunlaus

**Comment by hueyyeng** [comment]
@Gunlaus I'll need time to review my changes for improvements to allow recursive unpack DAT and extract SVO before I merge into develop branch.

Do checkout to this branch if you want to test it out: https://github.com/hueyyeng/VesperiaTools/tree/feature/VT-4-add-unpack-data-extract-svo-to-gui

**Comment by Gunlaus** [comment]
I just did a test file, and was given this error

`System.Exception: zlib based tlzc compression currently unavailable, use revision https://github.com/AdmiralCurtiss/HyoutaTools/tree/525209cc0ada7d54f1a67f6f82c28c3e6cd0f722 for now
   at HyoutaTools.Tales.tlzc.TLZC.Compression2.Decompress(Byte[] buffer) in D:\HyoutaTools\Tales\tlzc\TLZC.cs:line 78
   at HyoutaTools.Tales.tlzc.tlzcmain.Execute(List`1 args) in D:\HyoutaTools\Tales\tlzc\tlzcmain.cs:line 58`

**Comment by hueyyeng** [comment]
Which DAT file do you test with? The error relates to HyoutaTools TLZC compression but I just compiled the latest HyoutaTools commit to ensure I did not hit any regression.

I did several tests and it works fine on my end. Refer to screenshots.

![image](https://user-images.githubusercontent.com/15846423/111168477-0e5a5600-85dd-11eb-9c32-d3723d847f56.png)

![image](https://user-images.githubusercontent.com/15846423/111168694-482b5c80-85dd-11eb-97dd-8cb0696e7e0d.png)

How are you compiling the HyoutaTools? I recommend git clone the repo using the latest master branch and don't forget to run `git submodule update --init --recursive` in HyoutaTools folder as AdmiralCurtiss move out some of the code into different repos.

Ah I see you have open an issue at HyoutaTools.

My suggestion is to at least install Git for Windows and learn the basics of git clone and checkout. It will be easier to troubleshoot the issues if we're on the same page and if you're already eager to learn ESRGAN for model training, this will be the first step in exploring more interesting GitHub repository on AI upscaling!

**Comment by Gunlaus** [comment]
I would like to thank you with all my heart for your help. This has been incredibly frustrating for me but I have finally reached the end of the road (With good results!). I have successfully unpacked map.svo and got ALL the textures from it. I just want to confirm with you one last time, that IS the only place with background textures correct? My dataset needs as much as I can get. 

I'd like to also clear some things out, I do have `git` installed (In fact, I needed/used it for esrgan) but I just figured manually downloading would produce the same result. Somehow I kept messing up the directories one way or another and I couldn't figure out what's going on. A switch to `git` made all of my problems disappear. I was even able to pull the textures using CLI! 

I can finally relax. 

(Sanity check/ verify check: I've pulled 4897 textures files from map.svo)

**Comment by hueyyeng** [comment]
If you're looking for the background environment textures, `map.svo` should be the one stop place.

`chara.svo` is obviously for the characters model. Can't say I've scoured every nook and gritty of the game packages since the dev duplicated some of the assets in different packages to speed up the load time as mentioned before.

Using `git` is preferred when dealing with versioned controlled codes as downloading multiple ZIPs of the repo is tedious (for me anyway).

I'll still leave this issue open up first until I get the recursive feature working. I saw AdmiralCurtiss wrote a function to recursively unpack the TXM/TXV files but I prefer if the user have specific DAT files that they want to unpack instead of the whole SVO package.

**Comment by hueyyeng** [comment]
Decided to skip recursive unpack since it opens up a whole new can of if else worms.

**Comment by eggkershall** [comment]
How do I get that program running, do I click the main.py? itdoesn;t seem to work for me

**Comment by hueyyeng** [comment]
> How do I get that program running, do I click the main.py? itdoesn;t seem to work for me

You will need to follow this steps: https://github.com/hueyyeng/VesperiaTools#running-vesperiatools

**Comment by eggkershall** [comment]
sorry if I sound like a noob, but do I need to use it from the command prompt? is so, then it just fives me a error and closes

**Comment by hueyyeng** [comment]
Yes you will need to run it from the command prompt and also have Python 3.8 or newer installed.

I just tested steps provided and it is working on my side.

**Comment by eggkershall** [comment]
So I got VesperiaTools running but it asking for HyoutaToolsCLI.exe

so where would I get it?

**Comment by hueyyeng** [comment]
I believe you downloaded the tag release which is not the latest code as I already remove HyoutaToolsCLI.exe dependencies from my latest develop branch.

Can you download this and replace the existing files?

![image](https://user-images.githubusercontent.com/15846423/207537062-41f2b9fe-0a6a-47ff-8bbc-fee0e3e177ac.png)

**Comment by eggkershall** [comment]
so I got the program running but I don't know how to extract it, althou not sure how to get the textures so did I miss something?

**Comment by hueyyeng** [comment]
> so I got the program running but I don't know how to extract it, althou not sure how to get the textures so did I miss something?

I'll need more details on what you have already attempted. The textures (which is DDS format if I recall correctly) is from TXM files that is packaged in DAT files. Try this:

1. Unpack the .DAT files
2. I think you'll need to unpack it again as it it will be .DAT.dec
3. There will be many folders which you can find the TXM files
4. Use Extract Textures from TXM/TXV to get the texture files

Reminder that I'll need you to at least described what you have attempted or I'll not provide further assistance as this tools is provided as it and meant for those who really want to inspect Vesperia file contents. Yes it can be frustrating without a guide but that goes without saying for most game ripping tools out there.

**Comment by eggkershall** [comment]
Sorry for not being detailed earlier, I want to know does it work on the PC or PS3 ver,, and where would it be extracted to cuz I tried it and it seems like nothing happen or I dunno where its extracted to, and also if this is only for the PS3, what the chance that it can extract the DLC costumes? hope that enough

**Comment by hueyyeng** [comment]
I only tested it with the PC version but I remember tested it for PS3
version too.

As I cannot share the game files, I'll later check again on my side.

**Comment by eggkershall** [comment]
well no need to share the files, I already got them, I just need to know where would it be extracted from SVO  and DAT files

**Comment by hueyyeng** [comment]
![image](https://user-images.githubusercontent.com/15846423/215314103-7b2ad990-abcc-4d50-b47f-882d4e55ba61.png)

@eggkershall Can you try download the latest develop branch and replace your existing copy (or if you're already familiar with git, just `git pull develop`). I made a minor tweak to the way textures and material are handled.

You can try `FORT00.DAT` from `map.svo` and see if it matches like my screenshot. Take note there are "dummy files" for the lack of better term where you'll not be able to extract any textures despite being detected as TXV files.
